### ISSUE TITLE
Add a print CSS to allow for a beautiful documentation printing

### ISSUE THREAD

**Issue by stickgrinder** [sparkfabrik/Locke#2]
Often the project documentation contains parts of interests for the customers or partners. Those parts are better exported to PDF for better fruition by tech-unsavvy people.

Having a proper print CSS is a great way  to print-to-pdf the documents.

**Comment by francescoben** [comment]
Sure, it would be great to have a print CSS, I will work on that over the next few days. Thanks for the feedback!

P.s.  If you've already done that, feel free to create a PR, I'll review it as soon as I can.

**Comment by stickgrinder** [comment]
Not yet but if I find the time I'll submit it!
